const listOfReposAndOwners = [
  // { repoName: 'Face-X', ownerName: 'akshitagupta15june' },
  // { repoName: 'kanban', ownerName: 'kunalkashyap855' },
  // { repoName: 'awesome-portfolio-websites', ownerName: 'smaranjitghose' },
  // { repoName: 'DocLense', ownerName: 'smaranjitghose' },
  // { repoName: 'doc2pen', ownerName: 'smaranjitghose' },
  // { repoName: 'img_ai_app_boilerplate', ownerName: 'smaranjitghose' },
  // { repoName: 'ArtCV', ownerName: 'smaranjitghose' },
  // { repoName: 'GitKundli', ownerName: 'smaranjitghose' },
  // { repoName: 'Rotten-Scripts', ownerName: 'HarshCasper' },
  // { repoName: 'GirlMeetup', ownerName: 'chehak123' },
  // { repoName: 'College-Library-Website', ownerName: 'urvashi-code1255' },
  // { repoName: 'Red-Hat-Mobil-App', ownerName: 'vilsi12' },
  // { repoName: 'Flutter-Tutorial-App', ownerName: 'infiniteoverflow' },
  // { repoName: 'CollegeAada', ownerName: 'Tejas1510' },
  // { repoName: 'Data-Structure-and-Algorithms', ownerName: 'Nivedita967' },
  // { repoName: 'Rudra', ownerName: 'Harshal0902' },
  // { repoName: 'Care4ther-', ownerName: 'unnati914' },
  // { repoName: 'IntrepidKey', ownerName: 'syedmazharaliraza' },
  // { repoName: 'MobiMart', ownerName: 'kavania2002' },
  // { repoName: 'KnowYourDonor', ownerName: 'arteevraina' },
  // { repoName: 'AshTech-AI_Personal_Voice_Assistant', ownerName: 'Ash515' },
  // { repoName: 'TextAnalyzer', ownerName: 'rockingrohit9639' },
  // { repoName: 'link-manager', ownerName: 'GP-Kulam' },
  // { repoName: 'GRAMtsy', ownerName: 'LOGOInd' },
  { repoName: 'quantum-algorithms', ownerName: 'proRamLOGO' },
  // { repoName: 'PICTOR', ownerName: 'NandeeshG' },
  // { repoName: 'UniVendor', ownerName: 'JINDAL-JJ' },
  // { repoName: 'DSA-guide', ownerName: 'ankitapuri' },
  // { repoName: 'easy-education', ownerName: 'luckykumarirai' },
  // { repoName: 'easy-job-intern', ownerName: 'pankajkumarbij' },
  // { repoName: 'SheHeroes', ownerName: 'shagun25' },
  // { repoName: 'chatte-R', ownerName: 'ridsuteri' },
  // { repoName: 'Awesome-JavaScript-Projects', ownerName: 'Vishal-raj-1' },
  // { repoName: 'DConsole', ownerName: 'RAJAGOPALAN-GANGADHARAN' },
  // { repoName: 'JS-OS', ownerName: 'RAJAGOPALAN-GANGADHARAN' },
  // { repoName: 'Terrorism-Analysis-with-Insights', ownerName: 'sahilrahman12' },
  // { repoName: 'drowsiness-detection', ownerName: 'dhrubajyoti89' },
  // { repoName: 'online-food-ordering-system', ownerName: 'prakharshreyash15' },
  // { repoName: 'College-Community', ownerName: 'ritwikranjan' },
  // { repoName: 'AutomateInstaPyBot', ownerName: 'harikanani' },
  // { repoName: 'Walmart-Sales-Prediction', ownerName: 'Starkultra' },
  // { repoName: 'OpenSourceEvents-Frontend', ownerName: 'Catalyst-IN' },
];

const validCrossWocLabels = [
  'crosswoc',
  'cwoc',
  'cross woc',
  'cross_woc',
  'cross-woc',
  'c-woc',
  'c woc',
  'c_woc',
];

module.exports = Object.freeze({
  validCrossWocLabels: validCrossWocLabels,
  listOfReposAndOwners: listOfReposAndOwners,
});
